// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.15.8
// source: api/ocp-resource-api/ocp-resource-api.proto

package ocp_resource_api

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResourceV1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId uint64 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Type   uint64 `protobuf:"varint,3,opt,name=type,proto3" json:"type,omitempty"`
	Status uint64 `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *ResourceV1) Reset() {
	*x = ResourceV1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ocp_resource_api_ocp_resource_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResourceV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceV1) ProtoMessage() {}

func (x *ResourceV1) ProtoReflect() protoreflect.Message {
	mi := &file_api_ocp_resource_api_ocp_resource_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceV1.ProtoReflect.Descriptor instead.
func (*ResourceV1) Descriptor() ([]byte, []int) {
	return file_api_ocp_resource_api_ocp_resource_api_proto_rawDescGZIP(), []int{0}
}

func (x *ResourceV1) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ResourceV1) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ResourceV1) GetType() uint64 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *ResourceV1) GetStatus() uint64 {
	if x != nil {
		return x.Status
	}
	return 0
}

type CreateResourceRequestV1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId uint64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Type   uint64 `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`
	Status uint64 `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *CreateResourceRequestV1) Reset() {
	*x = CreateResourceRequestV1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ocp_resource_api_ocp_resource_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateResourceRequestV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResourceRequestV1) ProtoMessage() {}

func (x *CreateResourceRequestV1) ProtoReflect() protoreflect.Message {
	mi := &file_api_ocp_resource_api_ocp_resource_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResourceRequestV1.ProtoReflect.Descriptor instead.
func (*CreateResourceRequestV1) Descriptor() ([]byte, []int) {
	return file_api_ocp_resource_api_ocp_resource_api_proto_rawDescGZIP(), []int{1}
}

func (x *CreateResourceRequestV1) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateResourceRequestV1) GetType() uint64 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *CreateResourceRequestV1) GetStatus() uint64 {
	if x != nil {
		return x.Status
	}
	return 0
}

type CreateResourceResponseV1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId uint64 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Type   uint64 `protobuf:"varint,3,opt,name=type,proto3" json:"type,omitempty"`
	Status uint64 `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *CreateResourceResponseV1) Reset() {
	*x = CreateResourceResponseV1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ocp_resource_api_ocp_resource_api_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateResourceResponseV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResourceResponseV1) ProtoMessage() {}

func (x *CreateResourceResponseV1) ProtoReflect() protoreflect.Message {
	mi := &file_api_ocp_resource_api_ocp_resource_api_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResourceResponseV1.ProtoReflect.Descriptor instead.
func (*CreateResourceResponseV1) Descriptor() ([]byte, []int) {
	return file_api_ocp_resource_api_ocp_resource_api_proto_rawDescGZIP(), []int{2}
}

func (x *CreateResourceResponseV1) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CreateResourceResponseV1) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateResourceResponseV1) GetType() uint64 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *CreateResourceResponseV1) GetStatus() uint64 {
	if x != nil {
		return x.Status
	}
	return 0
}

type DescribeResourceRequestV1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ResourceId uint64 `protobuf:"varint,1,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
}

func (x *DescribeResourceRequestV1) Reset() {
	*x = DescribeResourceRequestV1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ocp_resource_api_ocp_resource_api_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DescribeResourceRequestV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeResourceRequestV1) ProtoMessage() {}

func (x *DescribeResourceRequestV1) ProtoReflect() protoreflect.Message {
	mi := &file_api_ocp_resource_api_ocp_resource_api_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeResourceRequestV1.ProtoReflect.Descriptor instead.
func (*DescribeResourceRequestV1) Descriptor() ([]byte, []int) {
	return file_api_ocp_resource_api_ocp_resource_api_proto_rawDescGZIP(), []int{3}
}

func (x *DescribeResourceRequestV1) GetResourceId() uint64 {
	if x != nil {
		return x.ResourceId
	}
	return 0
}

type ListResourcesRequestV1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Limit  uint64 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset uint64 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
}

func (x *ListResourcesRequestV1) Reset() {
	*x = ListResourcesRequestV1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ocp_resource_api_ocp_resource_api_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListResourcesRequestV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResourcesRequestV1) ProtoMessage() {}

func (x *ListResourcesRequestV1) ProtoReflect() protoreflect.Message {
	mi := &file_api_ocp_resource_api_ocp_resource_api_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResourcesRequestV1.ProtoReflect.Descriptor instead.
func (*ListResourcesRequestV1) Descriptor() ([]byte, []int) {
	return file_api_ocp_resource_api_ocp_resource_api_proto_rawDescGZIP(), []int{4}
}

func (x *ListResourcesRequestV1) GetLimit() uint64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListResourcesRequestV1) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListResourcesResponseV1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Resources []*ResourceV1 `protobuf:"bytes,1,rep,name=resources,proto3" json:"resources,omitempty"`
}

func (x *ListResourcesResponseV1) Reset() {
	*x = ListResourcesResponseV1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ocp_resource_api_ocp_resource_api_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListResourcesResponseV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResourcesResponseV1) ProtoMessage() {}

func (x *ListResourcesResponseV1) ProtoReflect() protoreflect.Message {
	mi := &file_api_ocp_resource_api_ocp_resource_api_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResourcesResponseV1.ProtoReflect.Descriptor instead.
func (*ListResourcesResponseV1) Descriptor() ([]byte, []int) {
	return file_api_ocp_resource_api_ocp_resource_api_proto_rawDescGZIP(), []int{5}
}

func (x *ListResourcesResponseV1) GetResources() []*ResourceV1 {
	if x != nil {
		return x.Resources
	}
	return nil
}

type RemoveResourceRequestV1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ResourceId uint64 `protobuf:"varint,1,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
}

func (x *RemoveResourceRequestV1) Reset() {
	*x = RemoveResourceRequestV1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ocp_resource_api_ocp_resource_api_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveResourceRequestV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveResourceRequestV1) ProtoMessage() {}

func (x *RemoveResourceRequestV1) ProtoReflect() protoreflect.Message {
	mi := &file_api_ocp_resource_api_ocp_resource_api_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveResourceRequestV1.ProtoReflect.Descriptor instead.
func (*RemoveResourceRequestV1) Descriptor() ([]byte, []int) {
	return file_api_ocp_resource_api_ocp_resource_api_proto_rawDescGZIP(), []int{6}
}

func (x *RemoveResourceRequestV1) GetResourceId() uint64 {
	if x != nil {
		return x.ResourceId
	}
	return 0
}

type RemoveResourceResponseV1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RemoveResourceResponseV1) Reset() {
	*x = RemoveResourceResponseV1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ocp_resource_api_ocp_resource_api_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveResourceResponseV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveResourceResponseV1) ProtoMessage() {}

func (x *RemoveResourceResponseV1) ProtoReflect() protoreflect.Message {
	mi := &file_api_ocp_resource_api_ocp_resource_api_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveResourceResponseV1.ProtoReflect.Descriptor instead.
func (*RemoveResourceResponseV1) Descriptor() ([]byte, []int) {
	return file_api_ocp_resource_api_ocp_resource_api_proto_rawDescGZIP(), []int{7}
}

var File_api_ocp_resource_api_ocp_resource_api_proto protoreflect.FileDescriptor

var file_api_ocp_resource_api_ocp_resource_api_proto_rawDesc = []byte{
	0x0a, 0x2b, 0x61, 0x70, 0x69, 0x2f, 0x6f, 0x63, 0x70, 0x2d, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x2d, 0x61, 0x70, 0x69, 0x2f, 0x6f, 0x63, 0x70, 0x2d, 0x72, 0x65, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x2d, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10, 0x6f,
	0x63, 0x70, 0x2e, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x2e, 0x61, 0x70, 0x69, 0x1a,
	0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f,
	0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x61, 0x0a,
	0x0a, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x56, 0x31, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x75,
	0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x75, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x22, 0x5e, 0x0a, 0x17, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x56, 0x31, 0x12, 0x17, 0x0a, 0x07, 0x75,
	0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x75, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x22, 0x6f, 0x0a, 0x18, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x56, 0x31, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x17, 0x0a, 0x07,
	0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x75,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x22, 0x3c, 0x0a, 0x19, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x52, 0x65, 0x73,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x56, 0x31, 0x12, 0x1f,
	0x0a, 0x0b, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x0a, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x49, 0x64, 0x22,
	0x46, 0x0a, 0x16, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x56, 0x31, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d,
	0x69, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12,
	0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x22, 0x55, 0x0a, 0x17, 0x4c, 0x69, 0x73, 0x74, 0x52,
	0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x56, 0x31, 0x12, 0x3a, 0x0a, 0x09, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x6f, 0x63, 0x70, 0x2e, 0x72, 0x65, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x56, 0x31, 0x52, 0x09, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x22, 0x3a,
	0x0a, 0x17, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x56, 0x31, 0x12, 0x1f, 0x0a, 0x0b, 0x72, 0x65, 0x73,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a,
	0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x49, 0x64, 0x22, 0x1a, 0x0a, 0x18, 0x52, 0x65,
	0x6d, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x56, 0x31, 0x32, 0x9e, 0x04, 0x0a, 0x0e, 0x4f, 0x63, 0x70, 0x52, 0x65,
	0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x41, 0x70, 0x69, 0x12, 0x75, 0x0a, 0x10, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x56, 0x31, 0x12, 0x29, 0x2e,
	0x6f, 0x63, 0x70, 0x2e, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x56, 0x31, 0x1a, 0x1c, 0x2e, 0x6f, 0x63, 0x70, 0x2e, 0x72,
	0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x52, 0x65, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x56, 0x31, 0x22, 0x18, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x12, 0x22, 0x0d,
	0x2f, 0x76, 0x31, 0x2f, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x3a, 0x01, 0x2a,
	0x12, 0x84, 0x01, 0x0a, 0x12, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x52, 0x65, 0x73,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x56, 0x31, 0x12, 0x2b, 0x2e, 0x6f, 0x63, 0x70, 0x2e, 0x72, 0x65,
	0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x44, 0x65, 0x73, 0x63, 0x72,
	0x69, 0x62, 0x65, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x56, 0x31, 0x1a, 0x1c, 0x2e, 0x6f, 0x63, 0x70, 0x2e, 0x72, 0x65, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x56, 0x31, 0x22, 0x23, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x1d, 0x12, 0x1b, 0x2f, 0x76, 0x31, 0x2f,
	0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x2f, 0x7b, 0x72, 0x65, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x7d, 0x12, 0x7d, 0x0a, 0x0f, 0x4c, 0x69, 0x73, 0x74, 0x52,
	0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x56, 0x31, 0x12, 0x28, 0x2e, 0x6f, 0x63, 0x70,
	0x2e, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4c, 0x69,
	0x73, 0x74, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x56, 0x31, 0x1a, 0x29, 0x2e, 0x6f, 0x63, 0x70, 0x2e, 0x72, 0x65, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x56, 0x31, 0x22,
	0x15, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x0f, 0x12, 0x0d, 0x2f, 0x76, 0x31, 0x2f, 0x72, 0x65, 0x73,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x12, 0x8e, 0x01, 0x0a, 0x10, 0x52, 0x65, 0x6d, 0x6f, 0x76,
	0x65, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x56, 0x31, 0x12, 0x29, 0x2e, 0x6f, 0x63,
	0x70, 0x2e, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x52,
	0x65, 0x6d, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x56, 0x31, 0x1a, 0x2a, 0x2e, 0x6f, 0x63, 0x70, 0x2e, 0x72, 0x65, 0x73,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65,
	0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x56, 0x31, 0x22, 0x23, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x1d, 0x2a, 0x1b, 0x2f, 0x76, 0x31, 0x2f,
	0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x2f, 0x7b, 0x72, 0x65, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x7d, 0x42, 0x4a, 0x5a, 0x48, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6f, 0x7a, 0x6f, 0x6e, 0x63, 0x70, 0x2f, 0x6f, 0x63, 0x70,
	0x2d, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x2d, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x70,
	0x69, 0x2f, 0x6f, 0x63, 0x70, 0x2d, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x2d, 0x61,
	0x70, 0x69, 0x3b, 0x6f, 0x63, 0x70, 0x5f, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f,
	0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_ocp_resource_api_ocp_resource_api_proto_rawDescOnce sync.Once
	file_api_ocp_resource_api_ocp_resource_api_proto_rawDescData = file_api_ocp_resource_api_ocp_resource_api_proto_rawDesc
)

func file_api_ocp_resource_api_ocp_resource_api_proto_rawDescGZIP() []byte {
	file_api_ocp_resource_api_ocp_resource_api_proto_rawDescOnce.Do(func() {
		file_api_ocp_resource_api_ocp_resource_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_ocp_resource_api_ocp_resource_api_proto_rawDescData)
	})
	return file_api_ocp_resource_api_ocp_resource_api_proto_rawDescData
}

var file_api_ocp_resource_api_ocp_resource_api_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_api_ocp_resource_api_ocp_resource_api_proto_goTypes = []interface{}{
	(*ResourceV1)(nil),                // 0: ocp.resource.api.ResourceV1
	(*CreateResourceRequestV1)(nil),   // 1: ocp.resource.api.CreateResourceRequestV1
	(*CreateResourceResponseV1)(nil),  // 2: ocp.resource.api.CreateResourceResponseV1
	(*DescribeResourceRequestV1)(nil), // 3: ocp.resource.api.DescribeResourceRequestV1
	(*ListResourcesRequestV1)(nil),    // 4: ocp.resource.api.ListResourcesRequestV1
	(*ListResourcesResponseV1)(nil),   // 5: ocp.resource.api.ListResourcesResponseV1
	(*RemoveResourceRequestV1)(nil),   // 6: ocp.resource.api.RemoveResourceRequestV1
	(*RemoveResourceResponseV1)(nil),  // 7: ocp.resource.api.RemoveResourceResponseV1
}
var file_api_ocp_resource_api_ocp_resource_api_proto_depIdxs = []int32{
	0, // 0: ocp.resource.api.ListResourcesResponseV1.resources:type_name -> ocp.resource.api.ResourceV1
	1, // 1: ocp.resource.api.OcpResourceApi.CreateResourceV1:input_type -> ocp.resource.api.CreateResourceRequestV1
	3, // 2: ocp.resource.api.OcpResourceApi.DescribeResourceV1:input_type -> ocp.resource.api.DescribeResourceRequestV1
	4, // 3: ocp.resource.api.OcpResourceApi.ListResourcesV1:input_type -> ocp.resource.api.ListResourcesRequestV1
	6, // 4: ocp.resource.api.OcpResourceApi.RemoveResourceV1:input_type -> ocp.resource.api.RemoveResourceRequestV1
	0, // 5: ocp.resource.api.OcpResourceApi.CreateResourceV1:output_type -> ocp.resource.api.ResourceV1
	0, // 6: ocp.resource.api.OcpResourceApi.DescribeResourceV1:output_type -> ocp.resource.api.ResourceV1
	5, // 7: ocp.resource.api.OcpResourceApi.ListResourcesV1:output_type -> ocp.resource.api.ListResourcesResponseV1
	7, // 8: ocp.resource.api.OcpResourceApi.RemoveResourceV1:output_type -> ocp.resource.api.RemoveResourceResponseV1
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_ocp_resource_api_ocp_resource_api_proto_init() }
func file_api_ocp_resource_api_ocp_resource_api_proto_init() {
	if File_api_ocp_resource_api_ocp_resource_api_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_ocp_resource_api_ocp_resource_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResourceV1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ocp_resource_api_ocp_resource_api_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateResourceRequestV1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ocp_resource_api_ocp_resource_api_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateResourceResponseV1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ocp_resource_api_ocp_resource_api_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DescribeResourceRequestV1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ocp_resource_api_ocp_resource_api_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListResourcesRequestV1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ocp_resource_api_ocp_resource_api_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListResourcesResponseV1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ocp_resource_api_ocp_resource_api_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveResourceRequestV1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ocp_resource_api_ocp_resource_api_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveResourceResponseV1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_ocp_resource_api_ocp_resource_api_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_ocp_resource_api_ocp_resource_api_proto_goTypes,
		DependencyIndexes: file_api_ocp_resource_api_ocp_resource_api_proto_depIdxs,
		MessageInfos:      file_api_ocp_resource_api_ocp_resource_api_proto_msgTypes,
	}.Build()
	File_api_ocp_resource_api_ocp_resource_api_proto = out.File
	file_api_ocp_resource_api_ocp_resource_api_proto_rawDesc = nil
	file_api_ocp_resource_api_ocp_resource_api_proto_goTypes = nil
	file_api_ocp_resource_api_ocp_resource_api_proto_depIdxs = nil
}
